apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: logistic
spec:
  type: NodePort  # или LoadBalancer для продакшена
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000  # опционально
  - name: agent
    port: 50000
    targetPort: 50000