apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-builder
  namespace: logistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistic-builder
  template:
    metadata:
      labels:
        app: logistic-builder
    spec:
      containers:
      - name: logistic-builder
        image: tigeroff/logistic-builder:1.1
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80;https://+:443"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/app/certs/tls.crt"
        - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
          value: "/app/certs/tls.key"
        - name: Logging__LogLevel__Default
          value: "Information" 
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=logistic_db;Username=postgres;Password=root"
        - name: RestEndpointConfiguration__RestEndpoint
          value: "http://logistic-api/notifications/request/calculated"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: certs-volume
          mountPath: "/app/certs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /hc
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /hc
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 8
          failureThreshold: 1
      volumes:
      - name: certs-volume
        secret:
          secretName: tls-secret
          secretName: tls-secret