apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: logistic
data:
  init-bucket.sh: |
    #!/bin/sh
    # Скрипт для создания buckets при старте
    sleep 5
    mc alias set myminio http://localhost:9000 minioadmin minioadmin
    mc mb myminio/logistic-bucket --ignore-existing
    echo "Bucket initialization completed"