apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: logistic
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092
  selector:
    app: kafka