apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-api
  namespace: logistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistic-api
  template:
    metadata:
      labels:
        app: logistic-api
    spec:
      containers:
      - name: logistic-api
        image: tigeroff/logistic-api:1.3
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80;https://+:443"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/app/certs/tls.crt"
        - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
          value: "/app/certs/tls.key"
        - name: Logging__LogLevel__Default
          value: "Debug" 
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=logistic_db;Username=postgres;Password=root"
        - name: CamundaConfiguration__BaseUrl
          value: "http://camunda-bpmn-orchestrator/engine-rest/"
        - name: CamundaConfiguration__ProcessSuffix
          value: "process-definition/key/services-health-check-process/start"
        - name: CamundaConfiguration__LogisticBuilderUrl
          value: "http://logistic-builder/hc"
        - name: CamundaConfiguration__LogisticPaymentUrl
          value: "http://logistic-payment/actuator/health"
        - name: CamundaConfiguration__DelayBetweenChecks
          value: "00:00:30"
        - name: KafkaConfiguration_Host
          value: "kafka:9092"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: certs-volume
          mountPath: "/app/certs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /hc
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /hc
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 8
          failureThreshold: 1
      volumes:
      - name: certs-volume
        secret:
          secretName: tls-secret