apiVersion: v1
kind: Service
metadata:
  name: logistic-api
  namespace: logistic
spec:
  selector:
    app: logistic-api
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443