apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-client
  namespace: logistic 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistic-client
  template:
    metadata:
      labels:
        app: logistic-client
    spec:
      containers:
      - name: logistic-client
        image: tigeroff/logistic-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 80 
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 8
          failureThreshold: 1