apiVersion: v1
kind: Service
metadata:
  name: logistic-client
  namespace: logistic
spec:
  type: LoadBalancer
  selector:
    app: logistic-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 443